In [1]:
import pandas as pd

In [88]:
df=pd.read_csv('Deduplication Problem - Sample Dataset.csv')

In [3]:
df.head(8)

             ln       dob gn       fn
0      SMITH JR  01/03/68  F  WILLIAM
1  ROTHMEYER JR  01/03/68  F  WILLIAM
2       ASBY JR  01/03/68  F  WILLIAM
3     SALTER JR  01/03/68  F  WILLIAM
4     SALTER JR  01/03/68  F  WILLIAM
5      BLAND JR  21/02/62  F  WILLIAM
6      BLAND JR  21/02/62  F  WILLIAM
7      BLAND JR  21/02/62  F  WILLIAM

In [7]:
df.describe()

                   ln       dob   gn      fn
count             103       103  103     103
unique             28        22    2      26
top     MICHAELSON JR  07/10/37    M  HAROLD
freq               22        24   77      24

In [4]:
df.nunique()

ln     28
dob    22
gn      2
fn     26
dtype: int64

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
from sklearn.model_selection import GridSearchCV

In [10]:
Model=KNeighborsClassifier()

In [12]:
Final_Model=GridSearchCV(Model,param_grid={'n_neighbors':list(range(1,29))})

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
vectorizer=CountVectorizer()

In [16]:
Vect=vectorizer.fit_transform(df['fn'])

In [22]:
FirstName=Vect.toarray()

In [23]:
Vect=vectorizer.fit_transform(df['ln'])

In [24]:
LastName=Vect.toarray()

In [26]:
LastName.shape

(103, 25)

In [27]:
vectorizer.transform(['SMITH JR']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1]], dtype=int64)

In [28]:
df.dtypes

ln     object
dob    object
gn     object
fn     object
dtype: object

In [31]:
def Splitter(X):

TypeError: len() takes no keyword arguments

In [33]:
type(df['dob'])

pandas.core.series.Series

In [42]:
df['dob'].apply()

TypeError: apply() missing 1 required positional argument: 'func'

In [36]:
df.dtypes

ln             object
dob    datetime64[ns]
gn             object
fn             object
dtype: object

In [46]:
df['day']=pd.to_datetime(df['dob']).dt.day
df['month']=pd.to_datetime(df['dob']).dt.month
df['year']=pd.to_datetime(df['dob']).dt.year

In [49]:
df.drop('dob',axis=1,inplace=True)

In [52]:
df.drop(['ln','fn'],axis=1,inplace=True)

In [53]:
df

    gn  day  month  year
0    F    3      1  1968
1    F    3      1  1968
2    F    3      1  1968
3    F    3      1  1968
4    F    3      1  1968
5    F   21      2  2062
6    F   21      2  2062
7    F   21      2  2062
8    F   21      2  2062
9    F   21      2  2062
10   F   21      2  2062
11   F   21      2  2062
12   F   21      2  2062
13   F   21      2  2062
14   F    6      8  2054
15   F    6      8  2054
16   F   25     10  2053
17   F   25     10  2053
18   F   25     10  2053
19   F   25     10  2053
20   F   25     10  2053
21   F   25     10  2053
22   F   25     10  2053
23   M   25     10  2053
24   M   25     10  2053
25   M   25     10  2053
26   M   25     10  2053
27   M    5      1  2051
28   M   17      6  2048
29   M   17      6  2048
..  ..  ...    ...   ...
73   M   10      7  2037
74   M   10      7  2037
75   M   10      7  2037
76   M   10      7  2037
77   M   10      7  2037
78   M   10      7  2037
79   M   10      7  2037
80   M   10      7  2037
81   M   10      7  2037
82   M   10      7  2037
83   M   10      7  2037
84   M   10      7  2037
85   M   10      7  2037
86   M   10      7  2037
87   M   10      7  2037
88   M    7     10  2037
89   M    5      7  2037
90   M    5      7  2037
91   M    5      7  2037
92   M    5      7  2037
93   M    5      7  2037
94   M   24     11  2034
95   M   24     11  2034
96   M   24     11  2034
97   M   24     11  2034
98   M   24     11  2034
99   M   15     10  2032
100  F   12      6  2037
101  F   12      6  2037
102  F   12      6  2037

[103 rows x 4 columns]

In [54]:
df['FirstName']=FirstName
df['LastName']=LastName

ValueError: Wrong number of items passed 24, placement implies 1

In [58]:
pd.DataFrame(FirstName,FirstName.columns)

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [66]:
df['FirstName']=FirstName.tolist()
df['LastName']=LastName.tolist()

In [67]:
df

,gn,day,month,year,FirstName,LastName
0,F,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,F,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,F,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,F,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,F,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
6,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
7,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
8,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
9,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
10,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..."
11,F,21,2,2062,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
12,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
13,F,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
14,F,6,8,2054,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
15,F,6,8,2054,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
16,F,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
17,F,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
18,F,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
19,F,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
20,F,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
21,F,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
22,F,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..."
23,M,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
24,M,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
25,M,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
26,M,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
27,M,5,1,2051,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
28,M,17,6,2048,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
29,M,17,6,2048,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...
73,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
74,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
75,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
76,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
77,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
78,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
79,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
80,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
81,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
82,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
83,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
84,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..."
85,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..."
86,M,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..."
87,M,10,7,2037,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..."
88,M,7,10,2037,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..."
89,M,5,7,2037,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..."
90,M,5,7,2037,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..."
91,M,5,7,2037,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..."
92,M,5,7,2037,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..."
93,M,5,7,2037,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..."
94,M,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..."
95,M,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..."
96,M,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..."
97,M,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..."
98,M,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..."
99,M,15,10,2032,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..."
100,F,12,6,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, ..."
101,F,12,6,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."
102,F,12,6,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..."

In [69]:
XX=pd.get_dummies(df['gn'])

In [71]:
Final_1=pd.concat([df,XX],axis=1)
Final_1.drop('gn',axis=1,inplace=True)

In [72]:
Final_1

,day,month,year,FirstName,LastName,F,M
0,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
1,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
2,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
3,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
4,3,1,1968,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
5,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
6,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
7,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
8,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
9,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
10,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...",1,0
11,21,2,2062,"[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
12,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
13,21,2,2062,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
14,6,8,2054,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
15,6,8,2054,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
16,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
17,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
18,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
19,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
20,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
21,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
22,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,0
23,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
24,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
25,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
26,25,10,2053,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
27,5,1,2051,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
28,17,6,2048,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
29,17,6,2048,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
...,...,...,...,...,...,...,...
73,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
74,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
75,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
76,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
77,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
78,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
79,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
80,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
81,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
82,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
83,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,1
84,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...",0,1
85,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...",0,1
86,10,7,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ...",0,1
87,10,7,2037,"[0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0,1
88,7,10,2037,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0,1
89,5,7,2037,"[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0,1
90,5,7,2037,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0,1
91,5,7,2037,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0,1
92,5,7,2037,"[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0,1
93,5,7,2037,"[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...",0,1
94,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...",0,1
95,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...",0,1
96,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...",0,1
97,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...",0,1
98,24,11,2034,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ...",0,1
99,15,10,2032,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,1
100,12,6,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, ...",1,0
101,12,6,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",1,0
102,12,6,2037,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ...","[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ...",1,0

In [73]:
Final_Model.fit(Final_1)

TypeError: fit() missing 1 required positional argument: 'y'

In [74]:
from sklearn.cluster import KMeans

In [75]:
K=KMeans()

In [76]:
K.fit(Final_1)

ValueError: setting an array element with a sequence.

In [78]:
Final_2=Final_1.drop(['FirstName','LastName'],axis=1)

In [ ]:
kmeans_model = KMeans(n_clusters=3, random_state=1).fit(X)
>>> labels = kmeans_model.labels_
>>> metrics.silhouette_score(X, labels, metric='euclidean')

In [82]:
from sklearn.metrics import silhouette_score
for i in range(3,29):
    Kmeans_model=KMeans(n_clusters=i).fit(Final_2)
    labels=Kmeans_model.labels_
    print(i,silhouette_score(Final_2,labels,metric='euclidean'))

3 0.526274972782
4 0.569293377706
5 0.58034478583
6 0.633532502247
7 0.695963605738
8 0.765791508981
9 0.790680917848
10 0.824144584237
11 0.831231138346
12 0.846450729999
13 0.852235272699
14 0.862897458581
15 0.881211182006
16 0.898703156852
17 0.92389478335
18 0.911384043836
19 0.929417196184
20 0.939445383699
21 0.948882450157
22 0.956350846588
23 0.961165048544
24 0.961165048544
25 0.961165048544
26 0.961165048544
27 0.961165048544
28 0.961165048544

In [83]:
Final_2

     day  month  year  F  M
0      3      1  1968  1  0
1      3      1  1968  1  0
2      3      1  1968  1  0
3      3      1  1968  1  0
4      3      1  1968  1  0
5     21      2  2062  1  0
6     21      2  2062  1  0
7     21      2  2062  1  0
8     21      2  2062  1  0
9     21      2  2062  1  0
10    21      2  2062  1  0
11    21      2  2062  1  0
12    21      2  2062  1  0
13    21      2  2062  1  0
14     6      8  2054  1  0
15     6      8  2054  1  0
16    25     10  2053  1  0
17    25     10  2053  1  0
18    25     10  2053  1  0
19    25     10  2053  1  0
20    25     10  2053  1  0
21    25     10  2053  1  0
22    25     10  2053  1  0
23    25     10  2053  0  1
24    25     10  2053  0  1
25    25     10  2053  0  1
26    25     10  2053  0  1
27     5      1  2051  0  1
28    17      6  2048  0  1
29    17      6  2048  0  1
..   ...    ...   ... .. ..
73    10      7  2037  0  1
74    10      7  2037  0  1
75    10      7  2037  0  1
76    10      7  2037  0  1
77    10      7  2037  0  1
78    10      7  2037  0  1
79    10      7  2037  0  1
80    10      7  2037  0  1
81    10      7  2037  0  1
82    10      7  2037  0  1
83    10      7  2037  0  1
84    10      7  2037  0  1
85    10      7  2037  0  1
86    10      7  2037  0  1
87    10      7  2037  0  1
88     7     10  2037  0  1
89     5      7  2037  0  1
90     5      7  2037  0  1
91     5      7  2037  0  1
92     5      7  2037  0  1
93     5      7  2037  0  1
94    24     11  2034  0  1
95    24     11  2034  0  1
96    24     11  2034  0  1
97    24     11  2034  0  1
98    24     11  2034  0  1
99    15     10  2032  0  1
100   12      6  2037  1  0
101   12      6  2037  1  0
102   12      6  2037  1  0

[103 rows x 5 columns]

In [84]:
Kmeans_model=KMeans(n_clusters=i).fit(Final_2)

In [85]:
labels=Kmeans_model.labels_

In [86]:
labels

array([ 1,  1,  1,  1,  1,  3,  3,  3,  3,  3,  3,  3,  3,  3, 12, 12,  5,
        5,  5,  5,  5,  5,  5, 21, 21, 21, 21, 11, 13, 13, 16, 16, 16,  6,
        6,  7,  7,  7,  7,  7,  7,  7, 10, 10, 20, 18, 18,  0,  0,  0,  0,
        0,  0, 19, 19,  4,  4,  4,  4,  4,  4, 15, 15, 15,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8, 22,  2,  2,  2,  2,  2,  9,  9,  9,  9,  9, 14, 17, 17,
       17])

In [89]:
df

                ln       dob gn            fn
0         SMITH JR  01/03/68  F       WILLIAM
1     ROTHMEYER JR  01/03/68  F       WILLIAM
2          ASBY JR  01/03/68  F       WILLIAM
3        SALTER JR  01/03/68  F       WILLIAM
4        SALTER JR  01/03/68  F       WILLIAM
5         BLAND JR  21/02/62  F       WILLIAM
6         BLAND JR  21/02/62  F       WILLIAM
7         BLAND JR  21/02/62  F       WILLIAM
8       SHAFFER JR  21/02/62  F       WILLIAM
9       SHAFFER JR  21/02/62  F       WILLIAM
10       BLAND III  21/02/62  F       WILLIAM
11        BLAND JR  21/02/62  F          BILL
12           BLAND  21/02/62  F       WILLIAM
13        BLAND JR  21/02/62  F       WILLIAM
14        BLAND JR  08/06/54  F       WILLIAM
15        BLAND JR  08/06/54  F       WILLIAM
16        BLAND JR  25/10/53  F       WILLIAM
17        BLAND JR  25/10/53  F       WILLIAM
18      SHAFFER JR  25/10/53  F       WILLIAM
19       DUNCAN JR  25/10/53  F        THOMAS
20      CARLSON JR  25/10/53  F           ROY
21      CARLSON JR  25/10/53  F           RON
22       DUNCAN JR  25/10/53  F           ROY
23      MICHAELSON  25/10/53  M           ROY
24   MICHAELSON JR  25/10/53  M           ROY
25      MICHAELSON  25/10/53  M           ROY
26   MICHAELSON JR  25/10/53  M           ROY
27   MICHAELSON JR  01/05/51  M           ROY
28   MICHAELSON JR  17/06/48  M           ROY
29   MICHAELSON JR  17/06/48  M           ROY
..             ...       ... ..           ...
73       MELVIN JR  07/10/37  M        HAROLD
74       MELVIN JR  07/10/37  M        HAROLD
75       CHAVAS JR  07/10/37  M        HAROLD
76       CHAVAS JR  07/10/37  M        HAROLD
77       CHAVAS JR  07/10/37  M        HAROLD
78       CHAVAS JR  07/10/37  M        HAROLD
79   MICHAELSON JR  07/10/37  M        HAROLD
80   MICHAELSON JR  07/10/37  M        HAROLD
81        SMITH JR  07/10/37  M        HAROLD
82       CHAVAS JR  07/10/37  M        HAROLD
83       CHAVAS JR  07/10/37  M        HAROLD
84        FAGEN JR  07/10/37  M        HAROLD
85        FAGEN JR  07/10/37  M        HAROLD
86        FAGEN JR  07/10/37  M        GEORGE
87      GRIFFIN JR  07/10/37  M          DARH
88      GRIFFIN JR  10/07/37  M          DARL
89      GRIFFIN JR  07/05/37  M          DARL
90      GRIFFIN JR  07/05/37  M      CLIFFORD
91      GRIFFIN JR  07/05/37  M      CLIFFORD
92      GRIFFIN JR  07/05/37  M      CLIFFORD
93      GRIFFIN JR  07/05/37  M      CLARENCE
94           HANNA  24/11/34  M     ADDISON J
95           HANNA  24/11/34  M  ADDISON JOHN
96           HANNA  24/11/34  M       ADDISON
97           HANNA  24/11/34  M       ADDISON
98           HANNA  24/11/34  M       ADDISON
99     GALETICH JR  15/10/32  M       ADDISON
100   FUNARO JONES  06/12/37  F       HARRIET
101       FUNARO J  06/12/37  F       HARRIET
102         FUNARO  06/12/37  F       HARRIET

[103 rows x 4 columns]

In [90]:
vectorizer=CountVectorizer()

In [92]:
Vect=vectorizer.fit_transform(df['fn'])

In [93]:
Kmeans_model.fit(Vect.toarray())

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=28, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [94]:
Kmeans_model.labels_

array([ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 12,  3,  3,  3,  3,  3,
        3,  3, 17,  4, 14,  4,  4,  4,  4,  4,  4,  4,  4,  4, 19,  0, 21,
       15, 26, 26, 26, 26, 26, 13, 13,  2,  2,  2, 23, 22,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  9,  9, 10, 10,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1, 20, 18, 11, 11,  7,  7,  7, 16,  6, 24,  6,  6,  6,  6,  5,  5,
        5])

In [95]:
vectorizer.get_feature_names()

['addison',
 'bill',
 'bob',
 'clarence',
 'clifford',
 'darh',
 'darl',
 'donald',
 'george',
 'harold',
 'harriet',
 'jack',
 'james',
 'john',
 'kenneth',
 'lawrence',
 'owan',
 'owen',
 'robert',
 'ron',
 'ronald',
 'roy',
 'thomas',
 'william']

In [100]:
FirstNameCol=pd.DataFrame(Vect.toarray(),columns=vectorizer.get_feature_names())

In [104]:
vectorizer=CountVectorizer()
Vect=vectorizer.fit_transform(df['ln'])

In [111]:
SecondNameCol=pd.DataFrame(Vect.toarray(),columns=vectorizer.get_feature_names())
SecondNameCol

,asby,bland,cain,carlson,chavas,clark,duncan,fagen,funaro,galetich,...,jr,larson,lind,melvin,michaelson,mustapha,rothmeyer,salter,shaffer,smith
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
5,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
6,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
9,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
10,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
12,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
14,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
15,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
16,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
17,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
19,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
20,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
21,0,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
74,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
75,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
76,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
77,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
78,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
80,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
81,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
82,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
83,0,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
84,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
85,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
86,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
87,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
88,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
89,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
90,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
91,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
92,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
93,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
94,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
95,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,0,0,0,0,0,0,0,0,0,1,...,1,0,0,0,0,0,0,0,0,0
100,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
101,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
102,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [106]:
vectorizer.get_feature_names()

['asby',
 'bland',
 'cain',
 'carlson',
 'chavas',
 'clark',
 'duncan',
 'fagen',
 'funaro',
 'galetich',
 'griffin',
 'hanna',
 'houghton',
 'iii',
 'jones',
 'jr',
 'larson',
 'lind',
 'melvin',
 'michaelson',
 'mustapha',
 'rothmeyer',
 'salter',
 'shaffer',
 'smith']

In [108]:
Vect.toarray().shape

(103, 25)

In [112]:
FirstNameCol.head()

,addison,bill,bob,clarence,clifford,darh,darl,donald,george,harold,...,kenneth,lawrence,owan,owen,robert,ron,ronald,roy,thomas,william
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [113]:
SecondNameCol.head()

,asby,bland,cain,carlson,chavas,clark,duncan,fagen,funaro,galetich,...,jr,larson,lind,melvin,michaelson,mustapha,rothmeyer,salter,shaffer,smith
0,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0

In [115]:
Final_3=pd.concat([Final_2,FirstNameCol,SecondNameCol],axis=1)

In [116]:
for i in range(3,29):
    Kmeans_model=KMeans(n_clusters=i).fit(Final_3)
    labels=Kmeans_model.labels_
    print(i,silhouette_score(Final_2,labels,metric='euclidean'))

3 0.523207301206
4 0.569293377706
5 0.58034478583
6 0.61313670593
7 0.693566392356
8 0.756897461971
9 0.790680917848
10 0.79406219667
11 0.831231138346
12 0.846450729999
13 0.857112915881
14 0.862897458581
15 0.881211182006
16 0.904019380569
17 0.92389478335
18 0.911384043836
19 0.929417196184
20 0.939445383699
21 0.946322659074
22 nan
23 nan

C:\Users\yashg\Anaconda3\lib\site-packages\sklearn\metrics\cluster\unsupervised.py:205: RuntimeWarning: invalid value encountered in true_divide
  sil_samples /= np.maximum(intra_clust_dists, inter_clust_dists)

24 nan
25 nan
26 nan
27 nan
28 nan

In [121]:
 Kmeans_model=KMeans(n_clusters=29).fit(Final_3)

In [122]:
Kmeans_model.labels_

array([ 1,  1,  1,  1,  1,  5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6, 18,
       18, 18, 18, 23, 23, 23,  2,  2,  2,  2, 13,  7,  7, 10, 10, 10, 21,
       21,  9,  9,  9,  9,  9, 26, 26, 14, 14, 25, 20, 20, 27, 27, 27, 11,
       11, 11,  4,  4, 16, 16, 16, 16, 16, 16, 15, 15, 15,  8,  8, 19, 19,
       19, 19, 19, 19, 19, 19, 19, 22, 22, 22, 22,  8,  8,  8, 22, 22,  8,
        8,  8, 28, 24,  0,  0,  0,  0,  0,  3,  3,  3,  3,  3, 12, 17, 17,
       17])

In [128]:
Final_3[['smith','william','jr','asby','salter']]

     smith  william  jr  asby  salter
0        1        1   1     0       0
1        0        1   1     0       0
2        0        1   1     1       0
3        0        1   1     0       1
4        0        1   1     0       1
5        0        1   1     0       0
6        0        1   1     0       0
7        0        1   1     0       0
8        0        1   1     0       0
9        0        1   1     0       0
10       0        1   0     0       0
11       0        0   1     0       0
12       0        1   0     0       0
13       0        1   1     0       0
14       0        1   1     0       0
15       0        1   1     0       0
16       0        1   1     0       0
17       0        1   1     0       0
18       0        1   1     0       0
19       0        0   1     0       0
20       0        0   1     0       0
21       0        0   1     0       0
22       0        0   1     0       0
23       0        0   0     0       0
24       0        0   1     0       0
25       0        0   0     0       0
26       0        0   1     0       0
27       0        0   1     0       0
28       0        0   1     0       0
29       0        0   1     0       0
..     ...      ...  ..   ...     ...
73       0        0   1     0       0
74       0        0   1     0       0
75       0        0   1     0       0
76       0        0   1     0       0
77       0        0   1     0       0
78       0        0   1     0       0
79       0        0   1     0       0
80       0        0   1     0       0
81       1        0   1     0       0
82       0        0   1     0       0
83       0        0   1     0       0
84       0        0   1     0       0
85       0        0   1     0       0
86       0        0   1     0       0
87       0        0   1     0       0
88       0        0   1     0       0
89       0        0   1     0       0
90       0        0   1     0       0
91       0        0   1     0       0
92       0        0   1     0       0
93       0        0   1     0       0
94       0        0   0     0       0
95       0        0   0     0       0
96       0        0   0     0       0
97       0        0   0     0       0
98       0        0   0     0       0
99       0        0   1     0       0
100      0        0   0     0       0
101      0        0   0     0       0
102      0        0   0     0       0

[103 rows x 5 columns]

In [126]:
Final_3.columns

Index(['day', 'month', 'year', 'F', 'M', 'addison', 'bill', 'bob', 'clarence',
       'clifford', 'darh', 'darl', 'donald', 'george', 'harold', 'harriet',
       'jack', 'james', 'john', 'kenneth', 'lawrence', 'owan', 'owen',
       'robert', 'ron', 'ronald', 'roy', 'thomas', 'william', 'asby', 'bland',
       'cain', 'carlson', 'chavas', 'clark', 'duncan', 'fagen', 'funaro',
       'galetich', 'griffin', 'hanna', 'houghton', 'iii', 'jones', 'jr',
       'larson', 'lind', 'melvin', 'michaelson', 'mustapha', 'rothmeyer',
       'salter', 'shaffer', 'smith'],
      dtype='object')

In [129]:
from sklearn.metrics import calinski_harabaz_score

In [140]:
for i in range(3,100):
    Kmeans_model=KMeans(n_clusters=i).fit(Final_3)
    labels=Kmeans_model.labels_
    print(i,silhouette_score(Final_3,labels))

3 0.507738660187
4 0.545656533518
5 0.547286146978
6 0.572115506765
7 0.634021377563
8 0.705417162817
9 0.72482865762
10 0.689386861542
11 0.720176652972
12 0.732962604955
13 0.740954546843
14 0.746632779571
15 0.759048031554
16 0.749085834865
17 0.720374663827
18 0.732577894324
19 0.743609684204
20 0.703296086523
21 0.694190524816
22 0.698417069694
23 0.693882234342
24 0.629782293732
25 0.655964622783
26 0.635340018888
27 0.652295995881
28 0.65303487642
29 0.710080045907
30 0.677847710742
31 0.699413860067
32 0.692894399254
33 0.674756824822
34 0.643489102752
35 0.646364267567
36 0.696633606013
37 0.676428434165
38 0.678447936931
39 0.667236685858
40 0.641554156058
41 0.697906408758
42 0.675617217492
43 0.637342319267
44 0.681175165198
45 0.657255234524
46 0.65562330959
47 0.652898838135
48 0.660520540685
49 0.666957047779
50 0.66127069208
51 0.676665785643
52 0.663369561362
53 0.662414360759
54 0.648914124917
55 0.652150370871
56 0.661859108735
57 0.65764576148
58 0.660407480416
59 0.653329060377
60 0.650485436893
61 0.650485436893
62 0.650485436893
63 0.650485436893
64 0.650485436893
65 0.650485436893
66 0.650485436893
67 0.650485436893
68 0.650485436893
69 0.650485436893
70 0.650485436893
71 0.650485436893
72 0.650485436893
73 0.650485436893
74 0.650485436893
75 0.650485436893
76 0.650485436893
77 0.650485436893
78 0.650485436893
79 0.650485436893
80 0.650485436893
81 0.650485436893
82 0.650485436893
83 0.650485436893
84 0.650485436893
85 0.650485436893
86 0.650485436893
87 0.650485436893
88 0.650485436893
89 0.650485436893
90 0.650485436893
91 0.650485436893
92 0.650485436893
93 0.650485436893
94 0.650485436893
95 0.650485436893
96 0.650485436893
97 0.650485436893
98 0.650485436893
99 0.650485436893

In [138]:
Kmeans_model=KMeans(n_clusters=65).fit(Final_3)
labels=Kmeans_model.labels_

In [139]:
labels

array([28, 55, 37,  1,  1,  5,  5,  5, 39, 39, 52, 54, 59,  5,  9,  9, 27,
       27, 19, 35, 20, 44, 47, 53,  0, 53,  0, 13,  8,  8, 14, 48, 50, 49,
       22, 24, 24, 24,  6,  6, 36, 36, 40, 12,  4, 51, 17, 57, 31, 31,  7,
        7,  7, 29, 29,  3,  3,  3, 26, 26, 41, 16, 30, 30, 38, 46,  2,  2,
        2,  2,  2,  2,  2,  2,  2, 21, 21, 21, 21, 34, 34, 45, 21, 21, 32,
       32, 25, 33, 23, 42, 10, 10, 10, 43, 11, 58, 11, 11, 11, 15, 56, 18,
       18])

In [145]:
Score=pd.DataFrame(labels,columns=['Similarity'])

In [149]:
pd.concat([df,Score],axis=1).to_csv("Unique.csv",index=False)